// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EndMenu: typeof import('./../src/components/end-menu/index.vue')['default']
    Footer: typeof import('./../src/components/footer/index.vue')['default']
    'IconAntDesign:settingOutlined': typeof import('~icons/ant-design/setting-outlined')['default']
    'IconBi:moonStarsFill': typeof import('~icons/bi/moon-stars-fill')['default']
    'IconBi:sunFill': typeof import('~icons/bi/sun-fill')['default']
    IconBxLock: typeof import('~icons/bx/lock')['default']
    IconBxUser: typeof import('~icons/bx/user')['default']
    IconClaritySearchLine: typeof import('~icons/clarity/search-line')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NavMenu: typeof import('./../src/components/nav-menu/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./../src/components/end-menu/setting-item.vue')['default']
    TitleBar: typeof import('./../src/components/title-bar/index.vue')['default']
    TopSearch: typeof import('./../src/components/top-search/index.vue')['default']
  }
}
